In [18]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series
import os
import matplotlib.pyplot as plt

In [22]:
# 数组的属性
np.random.seed(0)
x1 = np.random.randint(10, size=3) # 一维数组
x2 = np.random.randint(10, size=(4,3))
x3 = np.random.randint(10, size=(4,5,5))

In [23]:
# 数组的拼接
np.concatenate([x1, x1])
np.concatenate([x2, x2])

array([[3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [6]:
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)
big_array = np.random.randint(1,100,size=100000)
%timeit compute_reciprocals(big_array)

209 ms ± 35.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [16]:
# 高级通用特性函数
x = np.arange(10)
y = np.empty(10)
np.multiply(x, 10, out=y)
print(y)

y1 = np.arange(20)
np.power(2, x, out=y1[::2])
print(y1)

np.add.reduce(x)
np.add.accumulate(x)
np.multiply.outer(x, x)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]
[  1   1   2   3   4   5   8   7  16   9  32  11  64  13 128  15 256  17
 512  19]


array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [8]:
# 多维度聚合
M = np.random.random((3,4))
print(M)
print('M.min=', M.min(axis=1))

[[0.19042301 0.42646069 0.94185979 0.02082399]
 [0.57707129 0.96204145 0.95895488 0.83369279]
 [0.14098799 0.07059576 0.61219546 0.18624152]]
M.min= [0.02082399 0.57707129 0.07059576]


In [16]:
# 美国总统的平均身高的计算
# 数据位置/dataset/python数据科学手册/president_heights.csv
data = pd.read_csv('./codespace/python3/dataset/python数据科学手册/president_heights.csv')
data.columns

heights = np.array(data['height(cm)'])
print('mean heights:', heights.mean())
print('standard deviation:', heights.std())
print('min height:', heights.min())
print('max height:', heights.max())

mean heights: 179.73809523809524
standard deviation: 6.931843442745892
min height: 163
max height: 193


'/Users/machuan'