In [2]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series

In [8]:
data = {i : np.random.randn() for i in range(7)}
data

{0: 1.9986442996315197,
 1: -1.1858282672610576,
 2: -1.1834836462376748,
 3: 0.4159695573058502,
 4: 1.0423343189582777,
 5: 0.8219339485362952,
 6: 1.8052775845422853}

In [14]:
arr2d = np.array([[1,2,3], [4,5,6]])
print(arr2d)
print(arr2d[0])

[[1 2 3]
 [4 5 6]]
[1 2 3]
