In [3]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series

In [9]:
# 数组的属性
np.random.seed(0)
x1 = np.random.randint(10, size=6) # 一维数组
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))
grid = np.arange(1, 10).reshape(3,3)

print('x3 ndim:', x3.ndim)
print('x3 shape:', x3.shape)
print('x3 size:', x3.size)
print('x3 dtype:', x3.dtype)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 dtype: int64


In [18]:
# 数组的拼接
x = np.array([1,2,3])
y = np.array([3,2,1])
grid = np.arange(0,6).reshape(2,3)

print('1维数组拼接：' ,np.concatenate([x, y]))
print('\n2维数组拼接:\n', np.concatenate([grid, grid]))

1维数组拼接： [1 2 3 3 2 1]

2维数组拼接:
 [[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]


In [ ]:
# 数组的分裂
